development:
  adapter:  mysql2
  database: wgha_development
  host: 127.0.0.1
  username: root
  password: root
  socket:  /tmp/mysql.sock
  reconnect: true
  encoding: utf8mb4
  collation: utf8mb4_bin
  charset: utf8mb4

production:
  adapter:  mysql2
  database: wgha_development
  host: 127.0.0.1
  username: root
  password: root
  socket:  /tmp/mysql.sock
  reconnect: true
  encoding: utf8mb4
  collation: utf8mb4_bin
  charset: utf8mb4
