development:
  adapter:  mysql2
  database: wasgeht_development
  encoding: utf8
  username:     root
  password:
  socket: /tmp/mysql.sock
  reconnect: true

test:
  adapter:  mysql2
  database: wasgeht_test
  encoding: utf8
  username:     root
  password:
  socket: /tmp/mysql.sock
  reconnect: true
